# Site settings
title: Stuart A. Scott Laboratory
short_title: Scott Lab
email: your-email@domain.com
<<<<<<< HEAD
url: http://stuartscottlab.org
description:  "Website for the lab of Dr. Stuart A. Scott"
=======
url: https://example.github.io
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."
skills: "Web Developer - Graphic Artist - User Experience Designer"
meta_author: LastName FirstName
>>>>>>> jeromelachaud/master

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: myshortname

# Color settings (hex-codes without the leading hash-tag)
color:
<<<<<<< HEAD
  primary: 3A9DEB #80B3FF
  secondary: 18115F #FD6E8A
  secondary-dark: CC2679 #A2122F
=======
  primary: 18bc9c #80B3FF
  primary-rgb: "24,288,156" #"128,179,255"
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F
>>>>>>> jeromelachaud/master

# Footer settings
footer:
  copyright: Dr. Stuart A. Scott
  location: Location
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
# social:
#   - title: twitter
#     url: http://twitter.com/jekyllrb
#   - title: facebook
#     url:
#   - title: stack-overflow
#     url: http://stackoverflow.com/questions/tagged/jekyll
#   - title: bitbucket
#     url: http://bitbucket.org/jekyll
#   - title: github
#     url: http://github.com/jekyll

# Postal address (add as many lines as necessary)
address:
  - line: One Gustave L. Levy Place
  - line: New York, NY 10029-6574

# Credits content
credits: 'This site uses a modified version of Freelancer, a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com">Start Bootstrap</a>.'

sections:
  - title: Research
    template: "research.html"
  - title: People
    template: "people.html"
  - title: Publications
    template: "publications.html"
  - title: Teaching
    template: "one_col_content.html"
  - title: Resources
    template: "one_col_content.html"
  - title: Positions
    template: "one_col_content.html"
  - title: Contact
    template: "contact.html"

# Build settings
markdown: kramdown
permalink: pretty

# prose.io settings
prose:
  siteurl: 'scottlab.github.io'
  media: 'img'
  ignore:
    - index.md
    - _config.yml
    - /_layouts
    - /_includes
